# Create pipeline 
name: vijay-webapp containerization pipeline
# Trigger
on:
  push:
    branches:
      - "main"

# jobs for performing operations
jobs:
  vijay-image-build:
    runs-on: ubuntu-latest
    steps:
      - name: run some basic commands
        run: |
          uname -r
          whoami
          cat /etc/os-release 
          docker version
          docker-compose version

      - name: using pre-designed github workflow to get github repo to runners machine
        uses: actions/checkout@v4

      - name: verify github code
        run: ls -a      

      - name: use docker-compose
        run: |
          docker-compose down
          sleep 2
          docker-compose ps
          docker-compose up -d
          sleep 2
          docker-compose ps

      - name: Health-check
        test: curl --fail http://localhost:1235/health.html || exit 1
        interval: 60s       
        retries: 5
        start_period: 20s
        timeout: 10s
