name: vijay app containerization pipeline
# Trigger
on:
  push:
    branches:
      - "dev"

# creating multiple jobs
jobs:
  vijay-code-check-job:
    runs-on: ubuntu-latest
    steps:
      - name: checking only
        run: |
          echo "just checking"
          whoami

  vijay-sast-job:
    runs-on: windows-latest
    needs: vijay-code-check-job # it will wait for the job to complete before starting this job
    steps:
      - name: Checking docker version & snar version
        run: |
          docker version
          sonar-scanner --version
        
  vijay-build-job:
    runs-on: macos-latest
    needs: Vijay-sast-job 
    steps:
      - name: check general message
        run:
            echo "python version"
            pythong -V
