# Create pipeline 
name: vijay-webapp containerization pipeline
# Trigger
on:
  push:
    branches:
      - "main"

# jobs for performing operations
jobs:
  vijay-image-build:
    runs-on: ubuntu-latest
    steps:
      - name: run some basic commands
        run: |
          uname -r
          whoami
          cat /etc/os-release 
          docker version
          docker-compose version

      - name: using pre-designed github workflow to get github repo to runners machine
        uses: actions/checkout@v4

      - name: verify github code
        run: ls -a      

      - name: use docker-compose
        run: |
          docker-compose down
          sleep 2
          docker-compose ps
          docker-compose up -d
          sleep 2
          docker-compose ps

      - name: Health-check
        run: |
          curl http://localhost:1235/health.html 
          echo "access health.html and returns hml 200"

      - name: Try to login from runne to docker hub acc 
        uses: docker/login-action@v3
        with: 
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_PWD}}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: . # location of Dockerfile
          push: true
          tags: docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/vbmoui:version2

      - name: docker logout from runner fter pushing image
        run: docker logout    
